package com.shaowei.food.domain.enumeration;

/**
 * The Role enumeration.
 */
public enum Role {
    PROVIDER_ADMINISTRATOR, PROVIDER_SALES, PROVIDER_SALES_ADMINISTRATOR, PROVIDER_FORWARDER, TRADER_ADMINISTRATOR, TRADER_SALES, TRADER_SALES_ADMINISTRATOR, TRADER_ACCOUNTANT, TRADER_FORWARDER, BUYER_ADMINISTRATOR, BUYER_SALES, BUYER_SALES_ADMINISTRATOR, BUYER_FORWARDER, ROOT, ADMINISTRATOR
}
